export enum ESmartEnviosStatus {
  COLETADO = "COLETADO",
  EM_TRANSITO = "EM TRÂNSITO",
  EM_ROTA_ENTREGA = "EM ROTA DE ENTREGA",
  ENTREGA_REALIZADA = "ENTREGA REALIZADA",
  CANCELADO = "CANCELADO",
}
