version: "3"

services:
  # ms-tracking-manager:
  #   build:
  #     context: ./ms.loggi
  #     dockerfile: Dockerfile
  #   image: ms-tracking-manager
  #   ports:
  #     - "4000:4000"

  ms-carriers:
    build:
      context: ./ms.carriers
      dockerfile: Dockerfile
    image: ms-carriers
    ports:
      - "4001:4001"
    networks:
      - smartnetwork

  # web-tracking-view:
  #   build:
  #     context: ./web.tracking-view
  #     dockerfile: Dockerfile
  #   image: web-tracking-view
  #   ports:
  #     - "4002:4002"

  # Adicionar Kafka

  # Adicionar postgres

  # Adicionar PG Adimin

  # Adicionar o APM

networks:
  smartnetwork:
    driver: bridge
