version: "3"

services:
  ms-tracking-manager:
    image: ms-tracking-manager
    container_name: ms-tracking-manager
    build:
      context: ./ms.tracking-manager
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - smartnetwork

  ms-carriers:
    image: ms-carriers
    container_name: ms-carriers
    build:
      context: ./ms.carriers
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    networks:
      - smartnetwork

  # web-tracking-view:
  #   build:
  #     context: ./web.tracking-view
  #     dockerfile: Dockerfile
  #   image: web-tracking-view
  #   ports:
  #     - "4002:4002"

  # Adicionar Kafka

  # Adicionar postgres

  # Adicionar PG Adimin

  # Adicionar o APM

networks:
  smartnetwork:
    driver: bridge
